name: "Deploy to Heroku"
description: "Deploy an app to Heroku"
inputs:
  heroku_api_key:
    description: "This is needed for authentication. The API key can be found by going to your Heroku account settings."
    required: true
  heroku_app_name:
    description: "The app name to deploy to."
    required: true
  heroku_email:
    description: "The email of the Heroku app owner."
    required: true
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node20"
  main: "index.js"
